version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      target: build
    volumes:
      - ./src/app:/go/test-redis/src/app
    command: realize start --run --no-config
    ports:
      - 8000:8000
    depends_on:
      - redis
  #      - db

  #  db:
  #    image: mysql:5.7
  #    restart: always
  #    env_file:
  #      - .env
  #    ports:
  #      - 3306:3306
  #    volumes:
  #      - ./database/data:/var/lib/mysql
  #      - ./database/initdb:/docker-entrypoint-initdb.d
  #    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  redis:
    image: redis:latest
    ports:
      - 6379:6379
#    volumes:
#      - ./redis:/data


